<a href="https://colab.research.google.com/github/Shivanireddy102/AM/blob/main/student_performance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [3]:
import pandas as pd

# Load the dataset with the correct path and delimiter
df = pd.read_csv('/content/student-mat.csv', delimiter=';')

# Display the first few rows
print(df.head())

  school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        6   5   6   6  
1      5        3      3     1     1      3        4   5   5   6  
2      4        3      2     2     3      3       10   7   8  10  
3      3        2      2     1     1      5        2  15  14  15  
4      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]


In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64 
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64 
 7   Fedu        395 non-null    int64 
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64 
 13  studytime   395 non-null    int64 
 14  failures    395 non-null    int64 
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher    

In [5]:
df1 = pd.read_csv('/content/student-por.csv', delimiter=';')
df1.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 649 entries, 0 to 648
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   school      649 non-null    object
 1   sex         649 non-null    object
 2   age         649 non-null    int64 
 3   address     649 non-null    object
 4   famsize     649 non-null    object
 5   Pstatus     649 non-null    object
 6   Medu        649 non-null    int64 
 7   Fedu        649 non-null    int64 
 8   Mjob        649 non-null    object
 9   Fjob        649 non-null    object
 10  reason      649 non-null    object
 11  guardian    649 non-null    object
 12  traveltime  649 non-null    int64 
 13  studytime   649 non-null    int64 
 14  failures    649 non-null    int64 
 15  schoolsup   649 non-null    object
 16  famsup      649 non-null    object
 17  paid        649 non-null    object
 18  activities  649 non-null    object
 19  nursery     649 non-null    object
 20  higher    

In [6]:
df.shape

(395, 33)

In [7]:
print(df.describe())

              age        Medu        Fedu  traveltime   studytime    failures  \
count  395.000000  395.000000  395.000000  395.000000  395.000000  395.000000   
mean    16.696203    2.749367    2.521519    1.448101    2.035443    0.334177   
std      1.276043    1.094735    1.088201    0.697505    0.839240    0.743651   
min     15.000000    0.000000    0.000000    1.000000    1.000000    0.000000   
25%     16.000000    2.000000    2.000000    1.000000    1.000000    0.000000   
50%     17.000000    3.000000    2.000000    1.000000    2.000000    0.000000   
75%     18.000000    4.000000    3.000000    2.000000    2.000000    0.000000   
max     22.000000    4.000000    4.000000    4.000000    4.000000    3.000000   

           famrel    freetime       goout        Dalc        Walc      health  \
count  395.000000  395.000000  395.000000  395.000000  395.000000  395.000000   
mean     3.944304    3.235443    3.108861    1.481013    2.291139    3.554430   
std      0.896659    0.9988

In [8]:
df.columns.tolist()

['school',
 'sex',
 'age',
 'address',
 'famsize',
 'Pstatus',
 'Medu',
 'Fedu',
 'Mjob',
 'Fjob',
 'reason',
 'guardian',
 'traveltime',
 'studytime',
 'failures',
 'schoolsup',
 'famsup',
 'paid',
 'activities',
 'nursery',
 'higher',
 'internet',
 'romantic',
 'famrel',
 'freetime',
 'goout',
 'Dalc',
 'Walc',
 'health',
 'absences',
 'G1',
 'G2',
 'G3']

In [9]:
df.isnull().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

In [10]:
df.nunique()

school         2
sex            2
age            8
address        2
famsize        2
Pstatus        2
Medu           5
Fedu           5
Mjob           5
Fjob           5
reason         4
guardian       3
traveltime     4
studytime      4
failures       4
schoolsup      2
famsup         2
paid           2
activities     2
nursery        2
higher         2
internet       2
romantic       2
famrel         5
freetime       5
goout          5
Dalc           5
Walc           5
health         5
absences      34
G1            17
G2            17
G3            18
dtype: int64

In [11]:
df.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')

In [12]:
columns_to_drop = [
    'address', 'famsize', 'Pstatus', 'Mjob', 'Fjob', 'reason', 'guardian',
    'nursery', 'higher', 'activities', 'famrel', 'freetime', 'health'
]
df = df.drop(columns=columns_to_drop)
df.head()

school sex  age  Medu  Fedu  traveltime  studytime  failures schoolsup  \
0     GP   F   18     4     4           2          2         0       yes   
1     GP   F   17     1     1           1          2         0        no   
2     GP   F   15     1     1           1          2         3       yes   
3     GP   F   15     4     2           1          3         0        no   
4     GP   F   16     3     3           1          2         0        no   

  famsup paid internet romantic  goout  Dalc  Walc  absences  G1  G2  G3  
0     no   no       no       no      4     1     1         6   5   6   6  
1    yes   no      yes       no      3     1     1         4   5   5   6  
2     no  yes      yes       no      2     2     3        10   7   8  10  
3    yes  yes      yes      yes      2     1     1         2  15  14  15  
4    yes  yes       no       no      2     1     2         4   6  10  10

In [13]:
df.columns

Index(['school', 'sex', 'age', 'Medu', 'Fedu', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'internet', 'romantic',
       'goout', 'Dalc', 'Walc', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')

In [14]:
# List of columns to check unique values
columns_to_check = ['school', 'sex', 'schoolsup', 'famsup', 'paid', 'internet', 'romantic']
for col in columns_to_check:
    print(df[col].unique())


['GP' 'MS']
['F' 'M']
['yes' 'no']
['no' 'yes']
['no' 'yes']
['no' 'yes']
['no' 'yes']


In [15]:
from sklearn.preprocessing import LabelEncoder
columns_to_encode = ['sex', 'school', 'schoolsup', 'famsup', 'paid', 'internet', 'romantic']
label_encoder = LabelEncoder()
for col in columns_to_encode:
    df[col] = label_encoder.fit_transform(df[col])
df.head()

school  sex  age  Medu  Fedu  traveltime  studytime  failures  schoolsup  \
0       0    0   18     4     4           2          2         0          1   
1       0    0   17     1     1           1          2         0          0   
2       0    0   15     1     1           1          2         3          1   
3       0    0   15     4     2           1          3         0          0   
4       0    0   16     3     3           1          2         0          0   

   famsup  paid  internet  romantic  goout  Dalc  Walc  absences  G1  G2  G3  
0       0     0         0         0      4     1     1         6   5   6   6  
1       1     0         1         0      3     1     1         4   5   5   6  
2       0     1         1         0      2     2     3        10   7   8  10  
3       1     1         1         1      2     1     1         2  15  14  15  
4       1     1         0         0      2     1     2         4   6  10  10

In [21]:
df['G2'].unique()

array([ 6,  5,  8, 14, 10, 15, 12, 18, 16, 13,  9, 11,  7, 19, 17,  4,  0])

In [19]:
df['G1'].unique()

array([ 5,  7, 15,  6, 12, 16, 14, 10, 13,  8, 11,  9, 17, 19, 18,  4,  3])

In [20]:
df['G3'].unique()

array([ 6,  5,  8, 14, 10, 15, 12, 18, 16, 13,  9, 11,  7, 19, 17,  4,  0])

In [24]:
# Define the pass threshold for G3
threshold = 10
df['target_label'] = df['G3'].apply(lambda x: 'Pass' if x >= threshold else 'Fail')
print(df[['G3', 'target_label']])


    G3 target_label
0    6         Fail
1   10         Pass
2   15         Pass
3   11         Pass
4   19         Pass
5    9         Fail
6   12         Pass
7   14         Pass
8   16         Pass
9    5         Fail
10   8         Fail
11  17         Pass
12  18         Pass
13  13         Pass
14  20         Pass
15   7         Fail
16   0         Fail
17   4         Fail


In [37]:
from sklearn.model_selection import train_test_split

# Define X (features) and y (target)
X = df[['school', 'sex', 'age', 'Medu', 'Fedu', 'traveltime', 'studytime',
        'failures', 'schoolsup', 'famsup', 'paid', 'internet', 'romantic',
        'goout', 'Dalc', 'Walc', 'absences', 'G1', 'G2']]

y = df['G3']

# Split into training and testing datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


KeyError: "None of [Index(['school', 'sex', 'age', 'Medu', 'Fedu', 'traveltime', 'studytime',\n       'failures', 'schoolsup', 'famsup', 'paid', 'internet', 'romantic',\n       'goout', 'Dalc', 'Walc', 'absences', 'G1', 'G2'],\n      dtype='object')] are in the [columns]"

In [38]:
df.columns = df.columns.str.strip()


In [39]:
expected_cols = ['school', 'sex', 'age', 'Medu', 'Fedu', 'traveltime', 'studytime',
                 'failures', 'schoolsup', 'famsup', 'paid', 'internet', 'romantic',
                 'goout', 'Dalc', 'Walc', 'absences', 'G1', 'G2']

existing_cols = [col for col in expected_cols if col in df.columns]
X = df[existing_cols]


In [42]:
y = df['G3']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [46]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
model = LogisticRegression() # Create a Logistic Regression model
model.fit(X_train, y_train) # Train the model

ValueError: at least one array or dtype is required

In [49]:
# Standardize features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

ValueError: at least one array or dtype is required